//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:39:22 PM IST 
//


package com.springsoap.cpsinterface.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * GroupLeader增加GroupMember
 * 
 * <p>Java class for AddGroupMemberByGroupLeaderRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddGroupMemberByGroupLeaderRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvitedMSISDN" type="{http://cps.huawei.com/cpsinterface/common}MSISDNType"/&gt;
 *         &lt;element name="GroupRoleID" type="{http://cps.huawei.com/cpsinterface/common}IDType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddGroupMemberByGroupLeaderRequest", propOrder = {
    "invitedMSISDN",
    "groupRoleID"
})
public class AddGroupMemberByGroupLeaderRequest {

    @XmlElement(name = "InvitedMSISDN", required = true)
    protected String invitedMSISDN;
    @XmlElement(name = "GroupRoleID")
    protected String groupRoleID;

    /**
     * Gets the value of the invitedMSISDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvitedMSISDN() {
        return invitedMSISDN;
    }

    /**
     * Sets the value of the invitedMSISDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvitedMSISDN(String value) {
        this.invitedMSISDN = value;
    }

    /**
     * Gets the value of the groupRoleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupRoleID() {
        return groupRoleID;
    }

    /**
     * Sets the value of the groupRoleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupRoleID(String value) {
        this.groupRoleID = value;
    }

}
