//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:39:22 PM IST 
//


package com.springsoap.cpsinterface.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import com.springsoap.cpsinterface.common.GroupBeneficiary;


/**
 * 新增Group Beneficiary
 * 
 * <p>Java class for AddGroupBeneficiaryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddGroupBeneficiaryRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GroupBeneficiary" type="{http://cps.huawei.com/cpsinterface/common}GroupBeneficiary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddGroupBeneficiaryRequest", propOrder = {
    "groupBeneficiary"
})
public class AddGroupBeneficiaryRequest {

    @XmlElement(name = "GroupBeneficiary", required = true)
    protected GroupBeneficiary groupBeneficiary;

    /**
     * Gets the value of the groupBeneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link GroupBeneficiary }
     *     
     */
    public GroupBeneficiary getGroupBeneficiary() {
        return groupBeneficiary;
    }

    /**
     * Sets the value of the groupBeneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupBeneficiary }
     *     
     */
    public void setGroupBeneficiary(GroupBeneficiary value) {
        this.groupBeneficiary = value;
    }

}
