//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:39:22 PM IST 
//


package com.springsoap.cpsinterface.request;

import com.springsoap.cpsinterface.common.GroupMemberRoleListType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 修改GroupMember的Role
 * 
 * <p>Java class for ChangeGroupMemberRolesRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeGroupMemberRolesRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ChangedMSISDN" type="{http://cps.huawei.com/cpsinterface/common}MSISDNType"/&gt;
 *         &lt;element name="AddRoleList" type="{http://cps.huawei.com/cpsinterface/common}GroupMemberRoleListType" minOccurs="0"/&gt;
 *         &lt;element name="RemoveRoleList" type="{http://cps.huawei.com/cpsinterface/common}GroupMemberRoleListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeGroupMemberRolesRequest", propOrder = {
    "changedMSISDN",
    "addRoleList",
    "removeRoleList"
})
public class ChangeGroupMemberRolesRequest {

    @XmlElement(name = "ChangedMSISDN", required = true)
    protected String changedMSISDN;
    @XmlElement(name = "AddRoleList")
    protected GroupMemberRoleListType addRoleList;
    @XmlElement(name = "RemoveRoleList")
    protected GroupMemberRoleListType removeRoleList;

    /**
     * Gets the value of the changedMSISDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangedMSISDN() {
        return changedMSISDN;
    }

    /**
     * Sets the value of the changedMSISDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangedMSISDN(String value) {
        this.changedMSISDN = value;
    }

    /**
     * Gets the value of the addRoleList property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMemberRoleListType }
     *     
     */
    public GroupMemberRoleListType getAddRoleList() {
        return addRoleList;
    }

    /**
     * Sets the value of the addRoleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMemberRoleListType }
     *     
     */
    public void setAddRoleList(GroupMemberRoleListType value) {
        this.addRoleList = value;
    }

    /**
     * Gets the value of the removeRoleList property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMemberRoleListType }
     *     
     */
    public GroupMemberRoleListType getRemoveRoleList() {
        return removeRoleList;
    }

    /**
     * Sets the value of the removeRoleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMemberRoleListType }
     *     
     */
    public void setRemoveRoleList(GroupMemberRoleListType value) {
        this.removeRoleList = value;
    }

}
