//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:39:22 PM IST 
//


package com.springsoap.cpsinterface.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 根据组织shortcode和层级，查询指定层级的组织信息请求
 * 
 * <p>Java class for QueryOrgByHierLevelRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryOrgByHierLevelRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Shortcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HierLevel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryOrgByHierLevelRequest", propOrder = {
    "shortcode",
    "hierLevel"
})
public class QueryOrgByHierLevelRequest {

    @XmlElement(name = "Shortcode", required = true)
    protected String shortcode;
    @XmlElement(name = "HierLevel", required = true)
    protected String hierLevel;

    /**
     * Gets the value of the shortcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortcode() {
        return shortcode;
    }

    /**
     * Sets the value of the shortcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortcode(String value) {
        this.shortcode = value;
    }

    /**
     * Gets the value of the hierLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHierLevel() {
        return hierLevel;
    }

    /**
     * Sets the value of the hierLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHierLevel(String value) {
        this.hierLevel = value;
    }

}
