//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:39:22 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://cps.huawei.com/cpsinterface/common", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springsoap.cpsinterface.common;
